const EXACT_TRANSLATIONS: Record<string, string> = {
  Add: 'Додати',
  'Add Member': 'Додати учасника',
  'Add Project': 'Додати проєкт',
  'Add Task': 'Додати завдання',
  'Add Task to Plan': 'Додати завдання до плану',
  'Add Variable': 'Додати змінну',
  Activity: 'Активність',
  Agents: 'Агенти',
  Analytics: 'Аналітика',
  Actions: 'Дії',
  Navigation: 'Навігація',
  Views: 'Подання',
  Work: 'Робота',
  Collaborate: 'Співпраця',
  Organize: 'Організація',
  Agent: 'Агент',
  Human: 'Людина',
  System: 'Система',
  Bug: 'Помилка',
  'Add tag': 'Додати тег',
  'Add tag...': 'Додати тег…',
  'Add Step': 'Додати крок',
  All: 'Усі',
  'All assignees': 'Усі виконавці',
  'All sources': 'Усі джерела',
  'All tags selected': 'Усі теги вибрано',
  'All tasks are already in this plan': 'Усі завдання вже додано до цього плану',
  Allowed: 'Дозволені',
  'Allowed Values': 'Допустимі значення',
  'Assigned:': 'Призначено:',
  Autopilot: 'Автопілот',
  Back: 'Назад',
  'Back to channels': 'Назад до каналів',
  'Open Command Palette': 'Відкрити палітру команд',
  'Toggle Sidebar': 'Перемкнути бічну панель',
  'Toggle Director Panel': 'Перемкнути панель директора',
  'Maximize/Restore Director Panel': 'Розгорнути/відновити панель директора',
  'Create Backlog Task': 'Створити завдання в беклозі',
  'List View': 'Список',
  'Kanban View': 'Канбан',
  Blocked: 'Заблоковано',
  Cancel: 'Скасувати',
  Cancelled: 'Скасовано',
  'Cancel reason:': 'Причина скасування:',
  Charts: 'Графіки',
  Clear: 'Очистити',
  'Clear all': 'Очистити все',
  'Clear all filters': 'Очистити всі фільтри',
  'Clear search (Escape)': 'Очистити пошук (Escape)',
  Close: 'Закрити',
  'Close dialog': 'Закрити діалог',
  'Close navigation menu': 'Закрити меню навігації',
  'Close panel': 'Закрити панель',
  Completed: 'Завершено',
  'Completed Today': 'Завершено сьогодні',
  'Completed (7 Days)': 'Завершено (7 днів)',
  'Connection Error': 'Помилка підключення',
  Connecting: 'Підключення',
  'Connecting...': 'Підключення…',
  Connected: 'Підключено',
  Critical: 'Критичний',
  Copy: 'Копіювати',
  'Copy Path': 'Копіювати шлях',
  'Copy Relative Path': 'Копіювати відносний шлях',
  Create: 'Створити',
  'Create Channel': 'Створити канал',
  'Create Document': 'Створити документ',
  'Create Entity': 'Створити сутність',
  'Create Library': 'Створити бібліотеку',
  'Create Plan': 'Створити план',
  'Create Task': 'Створити завдання',
  'Create Team': 'Створити команду',
  'Create Template': 'Створити шаблон',
  'Create Workflow': 'Створити робочий процес',
  'Create Agent': 'Створити агента',
  'New Task': 'Нове завдання',
  Libraries: 'Бібліотеки',
  'All Documents': 'Усі документи',
  '0 docs': '0 документів',
  'No libraries yet': 'Бібліотек ще немає',
  'Create one': 'Створити',
  'No documents yet': 'Документів ще немає',
  'No documents match your search or filters': 'Документів за вашим запитом або фільтрами не знайдено',
  'Try adjusting your search or filters': 'Спробуйте змінити запит або фільтри',
  'Create documents to build your knowledge base': 'Створіть документи, щоб побудувати базу знань',
  'Drop to remove from library': 'Перетягніть, щоб вилучити з бібліотеки',
  'Version History': 'Історія версій',
  'Linked Documents': 'Пов’язані документи',
  'Loading documents...': 'Завантаження документів…',
  'Loading links...': 'Завантаження посилань…',
  'Failed to load links': 'Не вдалося завантажити посилання',
  'Document not found': 'Документ не знайдено',
  'Move to All Documents?': 'Перемістити до всіх документів?',
  'Move to All Documents': 'Перемістити до всіх документів',
  'Choose your workflow': 'Виберіть робочий процес',
  'Select how agents should interact with your codebase. You can change this later in Settings.': 'Виберіть, як агенти мають взаємодіяти з вашою кодовою базою. Це можна змінити пізніше в налаштуваннях.',
  Auto: 'Автоматично',
  'Fast iteration, no human review': 'Швидка ітерація без перевірки людиною',
  'Agents merge directly to main. Tests must pass. Best for solo developers and rapid prototyping.': 'Агенти зливають зміни безпосередньо в main. Тести мають пройти. Найкраще для самостійної розробки та швидкого прототипування.',
  'Human reviews before main': 'Перевірка людиною перед злиттям у main',
  'Agents merge to a review branch. You review and merge to main when ready. Best for teams wanting oversight without blocking agents.': 'Агенти зливають зміни у гілку перевірки. Ви перевіряєте й зливаєте їх у main, коли все готово. Найкраще для команд, яким потрібен контроль без блокування агентів.',
  Approve: 'Підтвердження',
  'Full control, explicit approval': 'Повний контроль і явне підтвердження',
  'Agents need permission for restricted actions. Merges via GitHub PRs. Best for production codebases and regulated environments.': 'Агентам потрібен дозвіл для обмежених дій. Злиття виконуються через GitHub PR. Найкраще для production-кодових баз і регульованих середовищ.',
  Continue: 'Продовжити',
  'Failed to save preset. Please try again.': 'Не вдалося зберегти набір. Спробуйте ще раз.',
  'Saved Layouts': 'Збережені макети',
  'Delete layout': 'Видалити макет',
  'Save Current Layout': 'Зберегти поточний макет',
  'Clear All Panes': 'Очистити всі панелі',
  'No Terminal Panes': 'Немає панелей термінала',
  'Save Layout': 'Зберегти макет',
  'Search agents...': 'Пошук агентів…',
  'Create Steward': 'Створити стюарда',
  'Loading agents...': 'Завантаження агентів…',
  'Loading pools...': 'Завантаження пулів…',
  'Create your first agent to start orchestrating AI work. Agents can work on tasks autonomously in isolated git worktrees.': 'Створіть першого агента, щоб почати оркеструвати роботу ШІ. Агенти можуть автономно виконувати завдання в ізольованих git-робочих деревах.',
  'Create stewards to automate maintenance tasks like merging branches and scanning documentation.': 'Створіть стюардів для автоматизації завдань обслуговування, як-от злиття гілок і перевірка документації.',
  'Create agent pools to control the maximum number of agents running concurrently. Pools help manage resource usage and agent scheduling.': 'Створіть пули агентів, щоб контролювати максимальну кількість агентів, що працюють одночасно. Пули допомагають керувати використанням ресурсів і плануванням агентів.',
  'Search merge requests...': 'Пошук запитів на злиття…',
  'Loading merge requests...': 'Завантаження запитів на злиття…',
  'Failed to load merge requests': 'Не вдалося завантажити запити на злиття',
  'Loading messages...': 'Завантаження повідомлень…',
  'Failed to load messages': 'Не вдалося завантажити повідомлення',
  'Delete channel': 'Видалити канал',
  'No documents available': 'Документів немає',
  'No documents match your search': 'Документів за вашим запитом не знайдено',
  'Failed to upload image': 'Не вдалося завантажити зображення',
  'Failed to send message. Please try again.': 'Не вдалося надіслати повідомлення. Спробуйте ще раз.',
  'Library (optional)': 'Бібліотека (необов’язково)',
  'Loading playbooks...': 'Завантаження плейбуків…',
  'No playbooks available': 'Плейбуків немає',
  'Create a playbook template first': 'Спочатку створіть шаблон плейбука',
  'Select a playbook...': 'Виберіть плейбук…',
  'Failed to create workflow': 'Не вдалося створити робочий процес',
  'Search in Files': 'Пошук у файлах',
  'Search in files...': 'Пошук у файлах…',
  'Open a workspace to search...': 'Відкрийте робочий простір для пошуку…',
  'Open a workspace to search files...': 'Відкрийте робочий простір для пошуку файлів…',
  'Loading workspace...': 'Завантаження робочого простору…',
  'Loading Workspace': 'Завантаження робочого простору',
  'No Results Found': 'Результатів не знайдено',
  'No Files Found': 'Файлів не знайдено',
  'No files match your search.': 'Файлів за вашим запитом не знайдено.',
  'Open file': 'Відкрити файл',
  Editor: 'Редактор',
  Explorer: 'Провідник',
  'No workspace open': 'Робочий простір не відкрито',
  'No messages': 'Немає повідомлень',
  'Loading older messages...': 'Завантаження старіших повідомлень…',
  'Loading providers...': 'Завантаження провайдерів…',
  'Failed to change provider': 'Не вдалося змінити провайдера',
  'Delete agent': 'Видалити агента',
  'Open in Workspace': 'Відкрити в робочому просторі',
  'View inbox': 'Переглянути вхідні',
  'Failed to load completion data': 'Не вдалося завантажити дані про завершення',
  'Failed to load task data': 'Не вдалося завантажити дані завдань',
  'Failed to load type data': 'Не вдалося завантажити дані типів',
  'Failed to load performance data': 'Не вдалося завантажити дані продуктивності',
  'Failed to load workload data': 'Не вдалося завантажити дані навантаження',
  'Failed to load priority data': 'Не вдалося завантажити дані пріоритетів',
  'Failed to load token usage data': 'Не вдалося завантажити дані використання токенів',
  'Failed to load provider data': 'Не вдалося завантажити дані провайдерів',
  'Failed to load error rate data': 'Не вдалося завантажити дані частоти помилок',
  'Cache Create': 'Створення кешу',
  'Select Document': 'Виберіть документ',
  'Search documents...': 'Пошук документів…',
  'Failed to fetch documents': 'Не вдалося отримати документи',
  'Failed to create document': 'Не вдалося створити документ',
  'Failed to fetch libraries': 'Не вдалося отримати бібліотеки',
  'Failed to create library': 'Не вдалося створити бібліотеку',
  'Failed to restore version': 'Не вдалося відновити версію',
  'No transcript available': 'Розшифровка недоступна',
  'No messages yet': 'Повідомлень ще немає',
  'No matching merge requests': 'Відповідних запитів на злиття не знайдено',
  'Please select a file': 'Виберіть файл',
  'Select a File': 'Виберіть файл',
  'Initializing editor...': 'Ініціалізація редактора…',
  'Failed to Load': 'Не вдалося завантажити',
  'Failed to load editor': 'Не вдалося завантажити редактор',
  'Create Pool': 'Створити пул',
  'Loading agents': 'Завантаження агентів',
  'Failed to load agents': 'Не вдалося завантажити агентів',
  'Loading pools': 'Завантаження пулів',
  'Loading replies': 'Завантаження відповідей',
  'Try a different search term': 'Спробуйте інший пошуковий запит',
  'Copy message': 'Копіювати повідомлення',
  'Reply in thread': 'Відповісти в гілці',
  'Cancel reply': 'Скасувати відповідь',
  'Delete message': 'Видалити повідомлення',
  'Loading thread': 'Завантаження гілки',
  'Loading session history': 'Завантаження історії сесії',
  'Agent is working': 'Агент працює',
  'Uploading': 'Завантаження',
  Created: 'Створено',
  Dashboard: 'Панель керування',
  'Database Size': 'Розмір бази даних',
  'Elements by Type': 'Елементи за типом',
  'Last Updated': 'Останнє оновлення',
  'WebSocket Clients': 'Клієнти WebSocket',
  Broadcasting: 'Трансляція',
  'Loading chart...': 'Завантаження графіка…',
  'Failed to load chart data': 'Не вдалося завантажити дані графіка',
  'No tasks to display': 'Немає завдань для відображення',
  'No assigned tasks': 'Немає призначених завдань',
  'Failed to load channels': 'Не вдалося завантажити канали',
  'Loading thread...': 'Завантаження гілки…',
  'Loading events...': 'Завантаження подій…',
  'Failed to load events': 'Не вдалося завантажити події',
  'Clear filters': 'Очистити фільтри',
  'Show': 'Показати',
  'Page': 'Сторінка',
  'of': 'з',
  'No items': 'Немає елементів',
  'Created:': 'Створено:',
  'Created by:': 'Автор:',
  Cut: 'Вирізати',
  Database: 'База даних',
  Delete: 'Видалити',
  'Delete Channel': 'Видалити канал',
  'Delete Library': 'Видалити бібліотеку',
  'Delete plan': 'Видалити план',
  'Delete Plan': 'Видалити план',
  'Delete project': 'Видалити проєкт',
  'Delete step': 'Видалити крок',
  'Delete variable': 'Видалити змінну',
  'Delete workflow': 'Видалити робочий процес',
  'Delete this workflow and all its tasks?': 'Видалити цей робочий процес і всі його завдання?',
  Deleting: 'Видалення',
  'Deleting...': 'Видалення…',
  Description: 'Опис',
  Dependencies: 'Залежності',
  Disconnected: 'Відключено',
  Documents: 'Документи',
  Done: 'Виконано',
  Draft: 'Чернетка',
  Deferred: 'Відкладено',
  Closed: 'Закрито',
  Review: 'Перевірка',
  Backlog: 'Беклог',
  Edit: 'Редагувати',
  'Edit Shortcut': 'Редагувати комбінацію',
  'Edit Step': 'Редагувати крок',
  'Edit Template': 'Редагувати шаблон',
  'Edit Variable': 'Редагувати змінну',
  Undo: 'Скасувати дію',
  Redo: 'Повторити дію',
  Bold: 'Напівжирний',
  Italic: 'Курсив',
  'Inline Code': 'Вбудований код',
  Strikethrough: 'Закреслення',
  Highlight: 'Виділення',
  'Heading 1': 'Заголовок 1',
  'Heading 2': 'Заголовок 2',
  'Heading 3': 'Заголовок 3',
  'Bullet List': 'Маркований список',
  'Numbered List': 'Нумерований список',
  Quote: 'Цитата',
  'Code Block': 'Блок коду',
  Divider: 'Роздільник',
  'Horizontal Rule': 'Горизонтальна лінія',
  'Insert Image': 'Вставити зображення',
  'Insert Emoji': 'Вставити емодзі',
  'Align Left': 'Вирівняти ліворуч',
  'Align Center': 'Вирівняти по центру',
  'Align Right': 'Вирівняти праворуч',
  Justify: 'Вирівняти по ширині',
  Enable: 'Увімкнути',
  End: 'Кінець',
  Entities: 'Сутності',
  Error: 'Помилка',
  'Error loading data': 'Помилка завантаження даних',
  'Error loading workflow': 'Помилка завантаження робочого процесу',
  Channels: 'Канали',
  'Direct Messages': 'Прямі повідомлення',
  'Failed': 'Не вдалося',
  Feature: 'Функція',
  'Failed to load activity': 'Не вдалося завантажити активність',
  'Failed to load document': 'Не вдалося завантажити документ',
  'Failed to load inbox': 'Не вдалося завантажити вхідні',
  'Failed to load libraries': 'Не вдалося завантажити бібліотеки',
  'Failed to load members': 'Не вдалося завантажити учасників',
  'Failed to load plan': 'Не вдалося завантажити план',
  'Failed to load ready tasks': 'Не вдалося завантажити готові завдання',
  'Failed to load stats': 'Не вдалося завантажити статистику',
  'Failed to load workflow': 'Не вдалося завантажити робочий процес',
  Filters: 'Фільтри',
  Finished: 'Завершено',
  'Find More': 'Знайти більше',
  'No comments yet': 'Коментарів ще немає',
  'No matching emojis': 'Відповідних емодзі не знайдено',
  'No parent (root library)': 'Без батьківської бібліотеки (коренева бібліотека)',
  'No transcript available for this session': 'Для цієї сесії немає розшифровки',
  'No user selected': 'Користувача не вибрано',
  'No notifications': 'Немає сповіщень',
  'No approval requests': 'Немає запитів на підтвердження',
  "You're all caught up!": 'Усе переглянуто!',
  'Please try refreshing the page': 'Спробуйте оновити сторінку',
  'Ready Tasks': 'Готові завдання',
  'Ready vs Blocked': 'Готові та заблоковані',
  'Recent Activity': 'Остання активність',
  'Reply to': 'Відповісти на',
  'Search Files': 'Пошук файлів',
  'Search...': 'Пошук…',
  'Search messages...': 'Пошук повідомлень…',
  'Search across all channels': 'Пошук у всіх каналах',
  'Search plans... (Press / to focus)': 'Пошук планів… (натисніть / для фокуса)',
  'Search tasks by title or ID...': 'Пошук завдань за назвою або ID…',
  'Server Info': 'Інформація про сервер',
  'System Overview': 'Огляд системи',
  'System Status': 'Стан системи',
  'Tasks Completed (Last 7 Days)': 'Завдання, завершені за останні 7 днів',
  'Total Tasks': 'Усього завдань',
  'Upload images to see them here': 'Завантажте зображення, щоб побачити їх тут',
  'View Diff': 'Переглянути diff',
  'View Logs': 'Переглянути журнали',
  'View Task': 'Переглянути завдання',
  'View Workflow': 'Переглянути робочий процес',
  'View Entity': 'Переглянути сутність',
  'View Team': 'Переглянути команду',
  'View Document': 'Переглянути документ',
  'View Plan': 'Переглянути план',
  'View MR': 'Переглянути запит на злиття',
  'View Conflicts': 'Переглянути конфлікти',
  'Workload by Agent': 'Навантаження за агентом',
  'Loading Stoneforge': 'Завантаження Stoneforge',
  'Failed to Load Data': 'Не вдалося завантажити дані',
  'Less': 'Менше',
  'More': 'Більше',
  'Tap again to view tasks': 'Натисніть ще раз, щоб переглянути завдання',
  'Click to view tasks': 'Натисніть, щоб переглянути завдання',
  'Click to view details': 'Натисніть, щоб переглянути деталі',
  'Nest this library under another library': 'Вкласти цю бібліотеку в іншу бібліотеку',
  'Select a Task': 'Виберіть завдання',
  'This may take a moment for large datasets': 'Для великих наборів даних це може тривати деякий час',
  'Select a message': 'Виберіть повідомлення',
  'Choose a message from the list to view its content': 'Виберіть повідомлення зі списку, щоб переглянути його вміст',
  'Tip: Use J/K keys to navigate': 'Порада: використовуйте клавіші J/K для навігації',
  'Select a user from the header dropdown to view their inbox': 'Виберіть користувача у випадаючому списку заголовка, щоб переглянути його вхідні',
  'To:': 'Кому:',
  'Direct messages': 'Прямі повідомлення',
  Mentions: 'Згадки',
  'Newest first': 'Спочатку нові',
  'Oldest first': 'Спочатку старі',
  'By sender': 'За відправником',
  'All priorities': 'Усі пріоритети',
  'All tags': 'Усі теги',
  'Unassigned': 'Не призначено',
  Tag: 'Тег',
  Tags: 'Теги',
  Role: 'Роль',
  Mode: 'Режим',
  Focus: 'Фокус',
  'Max Slots': 'Максимум слотів',
  Provider: 'Провайдер',
  Model: 'Модель',
  Any: 'Будь-який',
  Worker: 'Виконавець',
  Steward: 'Стюард',
  Capacity: 'Ємність',
  'Agent Types': 'Типи агентів',
  'Pool enabled': 'Пул увімкнено',
  'Used by:': 'Використовується:',
  'Awaiting review': 'Очікує перевірки',
  'Running tests...': 'Виконання тестів…',
  'Merging...': 'Злиття…',
  Minimal: 'Мінімальний',
  Simple: 'Простий',
  Moderate: 'Помірний',
  Complex: 'Складний',
  'Very Complex': 'Дуже складний',
  Assigned: 'Призначено',
  'Awaiting Merge': 'Очікує злиття',
  Testing: 'Тестування',
  Merging: 'Злиття',
  Merged: 'Злито',
  Conflict: 'Конфлікт',
  'Test Failed': 'Тест не пройдено',
  'N/A': 'Н/З',
  Single: 'Один',
  Columns: 'Колонки',
  Rows: 'Рядки',
  Grid: 'Сітка',
  'Create Fix Task': 'Створити завдання для виправлення',
  'Add Blocking Task': 'Додати блокувальне завдання',
  'Delete Task': 'Видалити завдання',
  'Reopen Task': 'Повторно відкрити завдання',
  'Reset Task': 'Скинути завдання',
  'Attach Document': 'Прикріпити документ',
  'Resume Session': 'Відновити сесію',
  'Uploading...': 'Завантаження…',
  'Uploading image...': 'Завантаження зображення…',
  'Esc Close': 'Esc — закрити',
  'Agent is working...': 'Агент працює…',
  'Loading session history...': 'Завантаження історії сесії…',
  'No session history available': 'Історія сесій недоступна',
  'Sessions will appear here after you start using this agent': 'Сесії з’являться тут після початку роботи з цим агентом',
  'Change Status': 'Змінити стан',
  'Delete Merge Request': 'Видалити запит на злиття',
  'Merge Request': 'Запит на злиття',
  Identifier: 'Ідентифікатор',
  Version: 'Версія',
  'Last Released': 'Останній випуск',
  Repository: 'Репозиторій',
  License: 'Ліцензія',
  Marketplace: 'Маркетплейс',
  List: 'Список',
  Kanban: 'Канбан',
  'Primary Sort': 'Основне сортування',
  'Secondary Sort': 'Додаткове сортування',
  'Secondary sort...': 'Додаткове сортування…',
  Configure: 'Налаштувати',
  'Dispatch paused': 'Диспетчеризацію призупинено',
  'Waking...': 'Пробудження…',
  'Wake Now': 'Пробудити зараз',
  'No Results': 'Немає результатів',
  'Failed to Load Extension': 'Не вдалося завантажити розширення',
  'Plain Text': 'Звичайний текст',
  'Connecting to language server...': 'Підключення до мовного сервера…',
  'In Progress': 'У процесі',
  Inbox: 'Вхідні',
  Loading: 'Завантаження',
  'Loading...': 'Завантаження…',
  'Loading activity...': 'Завантаження активності…',
  'Loading channels...': 'Завантаження каналів…',
  'Loading document...': 'Завантаження документа…',
  'Loading inbox...': 'Завантаження вхідних…',
  'Loading libraries...': 'Завантаження бібліотек…',
  'Loading members...': 'Завантаження учасників…',
  'Loading plan...': 'Завантаження плану…',
  'Loading ready tasks...': 'Завантаження готових завдань…',
  'Loading stats...': 'Завантаження статистики…',
  'Loading tasks...': 'Завантаження завдань…',
  'Loading workflow...': 'Завантаження робочого процесу…',
  Live: 'У прямому ефірі',
  Members: 'Учасники',
  Metrics: 'Метрики',
  Medium: 'Середній',
  'Merge Requests': 'Запити на злиття',
  Messages: 'Повідомлення',
  'No content': 'Немає вмісту',
  'No default': 'Без значення за замовчуванням',
  'No entities registered': 'Сутності не зареєстровано',
  'No images match your search': 'Зображень за вашим запитом не знайдено',
  'No images uploaded yet': 'Зображення ще не завантажено',
  'No library': 'Без бібліотеки',
  'No matching commands': 'Відповідних команд не знайдено',
  'No matching entities': 'Відповідних сутностей не знайдено',
  'No matching tasks found': 'Відповідних завдань не знайдено',
  'No messages found': 'Повідомлень не знайдено',
  'No messages match your filters': 'Немає повідомлень, що відповідають фільтрам',
  'No plans found': 'Планів не знайдено',
  'No plans to display in roadmap': 'Немає планів для відображення на часовій шкалі',
  'No projects registered': 'Проєкти не зареєстровані',
  'No results found.': 'Результатів не знайдено.',
  'No steps in this workflow': 'У цьому робочому процесі немає кроків',
  'No tasks in this plan': 'У цьому плані немає завдань',
  'No tasks in this workflow': 'У цьому робочому процесі немає завдань',
  'No users': 'Користувачів немає',
  None: 'Немає',
  'Not found': 'Не знайдено',
  Open: 'Відкрито',
  Optional: 'Необов’язково',
  Overview: 'Огляд',
  Paste: 'Вставити',
  Pending: 'Очікує',
  Plans: 'Плани',
  Polling: 'Опитування',
  'Press keys...': 'Натисніть клавіші…',
  Priority: 'Пріоритет',
  High: 'Високий',
  Low: 'Низький',
  Trivial: 'Незначний',
  Chore: 'Обслуговування',
  Task: 'Завдання',
  Running: 'Виконується',
  Succeeded: 'Успішно',
  Queued: 'У черзі',
  Paused: 'Призупинено',
  'Tests Failed': 'Тести не пройдено',
  'Merge Failed': 'Злиття не вдалося',
  'No Merge Needed': 'Злиття не потрібне',
  Progress: 'Прогрес',
  Projects: 'Проєкти',
  Public: 'Публічний',
  Private: 'Приватний',
  Refresh: 'Оновити',
  'Refresh projects': 'Оновити проєкти',
  Remove: 'Видалити',
  'Remove member': 'Видалити учасника',
  'Remove from plan': 'Видалити з плану',
  Rename: 'Перейменувати',
  Reconnecting: 'Повторне підключення',
  'Reconnecting...': 'Повторне підключення…',
  Required: 'Обов’язково',
  Reset: 'Скинути',
  'Reset All Shortcuts?': 'Скинути всі комбінації клавіш?',
  Retry: 'Повторити',
  Save: 'Зберегти',
  'Save Changes': 'Зберегти зміни',
  Search: 'Пошук',
  Searching: 'Пошук',
  'Searching...': 'Пошук…',
  Settings: 'Налаштування',
  'Select a step to edit': 'Виберіть крок для редагування',
  'Select a variable to edit': 'Виберіть змінну для редагування',
  'Select an option': 'Виберіть варіант',
  'Select entity...': 'Виберіть сутність…',
  'Select Project': 'Виберіть проєкт',
  'Select user': 'Виберіть користувача',
  Sessions: 'Сесії',
  Start: 'Запустити',
  Started: 'Запущено',
  'Started:': 'Запущено:',
  Status: 'Стан',
  Submit: 'Надіслати',
  Tasks: 'Завдання',
  'Tasks by Status': 'Завдання за станом',
  Teams: 'Команди',
  Timeline: 'Часова шкала',
  Today: 'Сьогодні',
  Yesterday: 'Учора',
  Input: 'Вхідні дані',
  Output: 'Вихідні дані',
  'Cache Read': 'Читання кешу',
  'Cache Creation': 'Створення кешу',
  Total: 'Усього',
  Updated: 'Оновлено',
  'Updated:': 'Оновлено:',
  Variables: 'Змінні',
  Workflows: 'Робочі процеси',
  Workspace: 'Робочий простір',
  Workspaces: 'Робочі простори',
  'Your search': 'Ваш пошук',
};

const ADDITIONAL_TRANSLATIONS: Record<string, string> = {
  'Reset to defaults': 'Скинути до типових',
  'Default Provider': 'Типовий провайдер',
  'Provider used by default when creating new agents': 'Провайдер, який типово використовується під час створення нових агентів',
  'Default Model per Provider': 'Типова модель для кожного провайдера',
  'Provider default': 'Типово для провайдера',
  'These models will be pre-selected when creating agents with the corresponding provider': 'Ці моделі буде попередньо вибрано під час створення агентів із відповідним провайдером',
  'Custom Executable Paths': 'Власні шляхи до виконуваних файлів',
  'Override the default executable path for each provider. Leave empty to use the system default.': 'Перевизначте типовий шлях до виконуваного файла для кожного провайдера. Залиште поле порожнім, щоб використовувати системний типовий шлях.',
  'Loading executable paths...': 'Завантаження шляхів до виконуваних файлів…',
  'Loading models...': 'Завантаження моделей…',
  '(not installed)': '(не встановлено)',
  Rotate: 'Обернути',
  'Add Pane': 'Додати панель',
  'No agents registered': 'Агентів не зареєстровано',
  'Cron Schedule': 'Розклад Cron',
  Event: 'Подія',
  'Select a workflow template...': 'Виберіть шаблон робочого процесу…',
  'Critical (P1)': 'Критичний (P1)',
  'High (P2)': 'Високий (P2)',
  'Medium (P3)': 'Середній (P3)',
  'Low (P4)': 'Низький (P4)',
  'Minimal (P5)': 'Мінімальний (P5)',
  'Delete Agent': 'Видалити агента',
  Navigate: 'Навігація',
  Title: 'Назва',
  'Session:': 'Сесія:',
  'Tests Passed': 'Тести пройдено',
  'Loading task...': 'Завантаження завдання…',
  'Closed:': 'Закрито:',
  'Set status back to open': 'Повернути стан «відкрито»',
  'Remove the assignee': 'Видалити виконавця',
  'Clear merge status': 'Очистити стан злиття',
  'Remove branch/worktree metadata': 'Видалити метадані гілки/робочого дерева',
  'Remove session ID': 'Видалити ідентифікатор сесії',
  'Loading transcript...': 'Завантаження розшифровки…',
  'Plan Progress': 'Прогрес плану',
  'Merge Pipeline': 'Конвеєр злиття',
  'Queue Health': 'Стан черги',
  'Oldest unassigned': 'Найстаріше непризначене',
  'Cache %': 'Кеш, %',
  Cost: 'Вартість',
  "Don't auto-dismiss": 'Не закривати автоматично',
  'Are you sure?': 'Ви впевнені?',
  Thread: 'Гілка',
  select: 'вибрати',
  close: 'закрити',
  'No tags': 'Тегів немає',
  'Entity not found': 'Сутність не знайдена',
  'This action cannot be undone.': 'Цю дію не можна скасувати.',
  'Plan not found': 'План не знайдено',
  'Workflow not found': 'Робочий процес не знайдено',
  'Completed:': 'Завершено:',
  'Cancelled:': 'Скасовано:',
  'Failure reason:': 'Причина помилки:',
  'Finished:': 'Завершено:',
  'Select...': 'Виберіть…',
  Ephemeral: 'Ефемерний',
  Steps: 'Кроки',
  'Step Type': 'Тип кроку',
  'Task Type': 'Тип завдання',
  Complexity: 'Складність',
  Assignee: 'Виконавець',
  'Default Value': 'Значення за замовчуванням',
  'or paste YAML below': 'або вставте YAML нижче',
  'Task Step': 'Крок завдання',
  'Agent-executed task': 'Завдання, виконуване агентом',
  'Function Step': 'Крок функції',
  'Execute code directly': 'Виконати код безпосередньо',
  'Alphanumeric, hyphens, underscores only': 'Лише літери, цифри, дефіси та підкреслення',
  'Private - Only members can see': 'Приватний — лише учасники можуть бачити',
  'Public - Anyone can see': 'Публічний — бачити можуть усі',
  'Invite Only': 'Лише за запрошенням',
  'Open - Anyone can join': 'Відкритий — приєднатися може будь-хто',
  'Request - Approval required': 'Запит — потрібне підтвердження',
  'Creator is automatically added': 'Творця буде додано автоматично',
  'Entities must be different': 'Сутності мають відрізнятися',
  'High cache hit rate': 'Високий коефіцієнт попадань у кеш',
  'Select a message to view': 'Виберіть повідомлення для перегляду',
  Restore: 'Відновити',
  'Mark as read': 'Позначити як прочитане',
  'Mark as unread': 'Позначити як непрочитане',
  Archive: 'Архівувати',
  'Condition (optional)': 'Умова (необов’язково)',
  'Remove trigger': 'Видалити тригер',
  'e.g., team-alpha, high-priority': 'наприклад, team-alpha, high-priority',
  'auto-detect (master/main)': 'автовизначення (master/main)',
  Every: 'Кожні',
  on: 'у',
  at: 'о',
  'on day': 'у день',
  '0 * * * * (every hour)': '0 * * * * (щогодини)',
  'Enter new name': 'Введіть нову назву',
  'Initial Message': 'Початкове повідомлення',
  'Enter task title': 'Введіть назву завдання',
  'e.g., Focus on the API endpoints first...': 'наприклад, спочатку зосередьтеся на кінцевих точках API…',
  Select: 'Вибрати',
  'Type a command or search...': 'Введіть команду або пошуковий запит…',
  'Go to line': 'Перейти до рядка',
  'Enter document title...': 'Введіть назву документа…',
  'Type and press comma to add tags': 'Введіть тег і натисніть кому, щоб додати його',
  Name: 'Назва',
  'Parent Library': 'Батьківська бібліотека',
  'Enter library name...': 'Введіть назву бібліотеки…',
  prev: 'назад',
  'Search extensions...': 'Пошук розширень…',
  'Clear search': 'Очистити пошук',
  'Unsaved changes': 'Незбережені зміни',
  'Close (Ctrl+W)': 'Закрити (Ctrl+W)',
  'Tip: Type': 'Порада: введіть',
  'Select Task': 'Виберіть завдання',
  Breadcrumb: 'Хлібні крихти',
  'Open navigation menu': 'Відкрити меню навігації',
  'Open command palette': 'Відкрити палітру команд',
  'Loading directors...': 'Завантаження директорів…',
  'Create Director': 'Створити директора',
  'Sift Backlog': 'Опрацювати беклог',
  'Start Session': 'Запустити сесію',
  'Restart Session': 'Перезапустити сесію',
  'Stop Session': 'Зупинити сесію',
  'Collapse Director Panel': 'Згорнути панель директора',
  'Director tabs': 'Вкладки директора',
  'Mark all as read': 'Позначити все як прочитане',
  'Process messages': 'Опрацювати повідомлення',
  'Dismiss rate limit banner': 'Закрити банер обмеження запитів',
  'Describe what needs to be fixed...': 'Опишіть, що потрібно виправити…',
  'Back to list': 'Назад до списку',
  'Merge request filters': 'Фільтри запитів на злиття',
  'Manage merge request': 'Керувати запитом на злиття',
  Notifications: 'Сповіщення',
  'Requests will appear here when agents need permission.': 'Запити з’являться тут, коли агентам знадобиться дозвіл.',
  'View details': 'Переглянути деталі',
  Dismiss: 'Закрити',
  'Notification sidebar': 'Бічна панель сповіщень',
  'Clear all notifications': 'Очистити всі сповіщення',
  'Notification settings': 'Налаштування сповіщень',
  'Close notification sidebar': 'Закрити бічну панель сповіщень',
  'Skip tour': 'Пропустити огляд',
  'Remove agent type': 'Видалити тип агента',
  'No limit': 'Без обмежень',
  'e.g., worker-pool, build-agents': 'наприклад, worker-pool, build-agents',
  'e.g., Pool for ephemeral build workers': 'наприклад, пул для тимчасових агентів збірки',
  'e.g., production, high-priority': 'наприклад, production, high-priority',
  'Select provider...': 'Виберіть провайдера…',
  'per page': 'на сторінку',
  'Items per page': 'Елементів на сторінку',
  'First page': 'Перша сторінка',
  'Previous page': 'Попередня сторінка',
  'Next page': 'Наступна сторінка',
  'Last page': 'Остання сторінка',
  'Jump to latest messages': 'Перейти до останніх повідомлень',
  'Scrollable list': 'Список із прокручуванням',
  'Filter & Sort': 'Фільтр і сортування',
  'Task actions': 'Дії із завданням',
  'Steward reviewing': 'Стюард перевіряє',
  'Closed but not merged': 'Закрито, але не злито',
  Deadline: 'Кінцевий термін',
  'Remove blocker': 'Видалити блокувальник',
  Reopen: 'Повторно відкрити',
  Reset: 'Скинути',
  'Reset task to open, clearing assignee and work data': 'Скинути завдання до стану «відкрито», очистивши виконавця та робочі дані',
  'Delete task': 'Видалити завдання',
  'Edit title': 'Редагувати назву',
  'Clear deadline': 'Очистити кінцевий термін',
  'Edit deadline': 'Редагувати кінцевий термін',
  'Type tag and press Enter...': 'Введіть тег і натисніть Enter…',
  'Edit tags': 'Редагувати теги',
  'Add a description (supports markdown)...': 'Додайте опис (підтримується Markdown)…',
  'Edit description': 'Редагувати опис',
  'Why is this task being reopened?': 'Чому це завдання відкривається повторно?',
  'Remove attachment': 'Видалити вкладення',
  'View transcript': 'Переглянути розшифровку',
  'Resume session': 'Відновити сесію',
  'Enter a message to send when resuming...': 'Введіть повідомлення для надсилання під час відновлення…',
  'Start task': 'Запустити завдання',
  'Complete task': 'Завершити завдання',
  'Reopen task': 'Повторно відкрити завдання',
  'List view (V L)': 'Подання списком (V L)',
  'Kanban view (V K)': 'Канбан-подання (V K)',
  'Open session': 'Відкрити сесію',
  'Delete transcript': 'Видалити розшифровку',
  'Open this session (send a message to resume)': 'Відкрити цю сесію (надіслати повідомлення для відновлення)',
  'Close transcript': 'Закрити розшифровку',
  'Send message (Enter)': 'Надіслати повідомлення (Enter)',
  'Swap sections': 'Поміняти розділи місцями',
  'Close tab': 'Закрити вкладку',
  'More options': 'Більше параметрів',
  'Close pane': 'Закрити панель',
  Uninstall: 'Видалити',
  Tabs: 'Вкладки',
  'No agents yet': 'Агентів ще немає',
  Directors: 'Директори',
  'Persistent Workers': 'Постійні виконавці',
  'Ephemeral Workers': 'Тимчасові виконавці',
  'No stewards yet': 'Стюардів ще немає',
  'No pools yet': 'Пулів ще немає',
  'Agent Pools': 'Пули агентів',
  'Document title': 'Назва документа',
  'Save changes': 'Зберегти зміни',
  'Cancel editing': 'Скасувати редагування',
  'Edit document': 'Редагувати документ',
  'Clone document': 'Клонувати документ',
  'Version history': 'Історія версій',
  'Exit fullscreen': 'Вийти з повноекранного режиму',
  'Exit fullscreen (Escape)': 'Вийти з повноекранного режиму (Escape)',
  'Enter fullscreen': 'Увійти в повноекранний режим',
  'Focus mode (fullscreen)': 'Режим фокусування (на весь екран)',
  'Enter document content...': 'Введіть вміст документа…',
  'Search documents by title or ID...': 'Пошук документів за назвою або ID…',
  'Open document': 'Відкрити документ',
  'Remove link': 'Видалити посилання',
  'Search docs... (/)': 'Пошук документів… (/)',
  'New Library': 'Нова бібліотека',
  'Close version history': 'Закрити історію версій',
  'Create new document': 'Створити новий документ',
  Document: 'Документ',
  'Editor Failed to Load': 'Не вдалося завантажити редактор',
  'New File': 'Новий файл',
  'New Folder': 'Нова папка',
  'Collapse All': 'Згорнути все',
  'Replying as': 'Відповідь від імені',
  Reply: 'Відповісти',
  'Write your reply...': 'Напишіть відповідь…',
  'Shortcuts:': 'Комбінації клавіш:',
  'New Channel': 'Новий канал',
  'Close thread': 'Закрити гілку',
  'Copy message (C when focused)': 'Копіювати повідомлення (C у фокусі)',
  'More actions': 'Більше дій',
  Send: 'Надіслати',
  'Attach image': 'Прикріпити зображення',
  'Attach document': 'Прикріпити документ',
  'Loading replies...': 'Завантаження відповідей…',
  'Reply in thread...': 'Відповісти в гілці…',
  'Create new channel': 'Створити новий канал',
  'No active plans with tasks': 'Немає активних планів із завданнями',
  'Activity & Distribution': 'Активність і розподіл',
  'Task Status Distribution': 'Розподіл завдань за станом',
  'Tasks by Type': 'Завдання за типом',
  'Agent Performance': 'Продуктивність агентів',
  'Current Workload by Agent': 'Поточне навантаження за агентами',
  'Plans & Pipeline': 'Плани та конвеєр',
  'Priority Analysis': 'Аналіз пріоритетів',
  'Open Tasks by Priority': 'Відкриті завдання за пріоритетом',
  'Provider and Model Analytics': 'Аналітика провайдерів і моделей',
  'per-model pricing': 'ціни за моделями',
  'Sessions by Provider': 'Сесії за провайдером',
  'Error Rate by Provider (%)': 'Частота помилок за провайдером (%)',
  'Loading agent...': 'Завантаження агента…',
  'Agent Not Found': 'Агента не знайдено',
  'Return to Workspaces': 'Повернутися до робочих просторів',
  'Add a project to get started': 'Додайте проєкт, щоб почати',
  'Settings tabs': 'Вкладки налаштувань',
  Theme: 'Тема',
  'Keyboard Shortcuts': 'Комбінації клавіш',
  'Agent Defaults': 'Типові параметри агента',
  'Onboarding Tour': 'Огляд для нових користувачів',
  'Custom executable path is set': 'Власний шлях до виконуваного файла задано',
  'Git Worktrees': 'Git-робочі дерева',
  'Ephemeral Tasks': 'Тимчасові завдання',
  'Steward Schedules': 'Розклади стюардів',
  'Reset All Settings': 'Скинути всі налаштування',
  Director: 'Директор',
  'Workflow Preset': 'Набір робочого процесу',
  'Remove project': 'Видалити проєкт',
  'No matching tasks': 'Відповідних завдань не знайдено',
  'Select all tasks': 'Вибрати всі завдання',
  'Rotate grid layout': 'Обернути макет сітки',
  'Layout name...': 'Назва макета…',
  'Document filters': 'Фільтри документів',
  'Channel creator': 'Творець каналу',
  'First Entity': 'Перша сутність',
  'Second Entity': 'Друга сутність',
  'Enter channel name...': 'Введіть назву каналу…',
  'Enter URL (e.g., https://example.com)': 'Введіть URL (наприклад, https://example.com)',
  'Apply link': 'Застосувати посилання',
  'Open link in new tab': 'Відкрити посилання в новій вкладці',
  Preview: 'Попередній перегляд',
  'Search images...': 'Пошук зображень…',
  'Enter plan title...': 'Введіть назву плану…',
  'Remove task': 'Видалити завдання',
  'No tasks in plan': 'У плані немає завдань',
  'Are you sure you want to delete': 'Ви впевнені, що хочете видалити',
  'This is the only task. Plans must have at least one task.': 'Це єдине завдання. Плани мають містити щонайменше одне завдання.',
  'Create plans to see them on the timeline': 'Створіть плани, щоб побачити їх на часовій шкалі',
  'List view': 'Подання списком',
  'Roadmap view': 'Подання дорожньою картою',
  Playbook: 'Плейбук',
  'Playbook actions': 'Дії плейбука',
  'Workflow actions': 'Дії робочого процесу',
  Runtime: 'Середовище виконання',
  Code: 'Код',
  Command: 'Команда',
  Type: 'Тип',
  required: 'обов’язково',
  'Move up': 'Перемістити вгору',
  'Move down': 'Перемістити вниз',
  'Step title': 'Назва кроку',
  'Step description': 'Опис кроку',
  'Paste YAML content here...': 'Вставте сюди вміст YAML…',
  'Editor tabs': 'Вкладки редактора',
  'Unknown error': 'Невідома помилка',
  'Pending Merge': 'Очікує злиття',
  'Awaiting Approval': 'Очікує підтвердження',
  View: 'Переглянути',
  'Close any open dialog or panel': 'Закрийте будь-який відкритий діалог або панель',
  'Navigate through lists and options': 'Переміщуйтеся списками та параметрами',
  'Select the current item or confirm action': 'Виберіть поточний елемент або підтвердьте дію',
  'Next/Previous': 'Далі/Назад',
  'Navigate items in inbox (vim-style)': 'Переміщення елементами вхідних (у стилі Vim)',
  Message: 'Повідомлення',
  'Pending merge': 'Очікує злиття',
  'Active Agents': 'Активні агенти',
  'In Review': 'На перевірці',
  'No unread messages': 'Немає непрочитаних повідомлень',
  'All caught up!': 'Усе переглянуто!',
  'This agent has no messages yet': 'У цього агента ще немає повідомлень',
  'No archived messages': 'Архівних повідомлень немає',
  'Archive messages to see them here': 'Архівуйте повідомлення, щоб побачити їх тут',
  Persistent: 'Постійний',
  Merge: 'Злиття',
  Docs: 'Документи',
  Recovery: 'Відновлення',
  Custom: 'Власний',
  Idle: 'Бездіяльний',
  Suspended: 'Призупинений',
  Stopped: 'Зупинений',
  Starting: 'Запускається',
  Unknown: 'Невідомо',
  'Failed to change model': 'Не вдалося змінити модель',
  'Failed to update triggers': 'Не вдалося оновити тригери',
  'Strategic agent that creates and assigns tasks. One per workspace.': 'Стратегічний агент, який створює та призначає завдання. Один на робочий простір.',
  'Execution agent that produces code and completes tasks.': 'Агент виконання, який створює код і завершує завдання.',
  'Support agent that performs automated maintenance tasks.': 'Допоміжний агент, який виконує автоматизовані завдання обслуговування.',
  'Merge Steward': 'Стюард злиття',
  'Handles merging completed branches, running tests, and cleanup.': 'Виконує злиття завершених гілок, запускає тести та очищення.',
  'Documentation Steward': 'Стюард документації',
  'Reviews, updates, and maintains workspace documents.': 'Перевіряє, оновлює та підтримує документи робочого простору.',
  'Recovery Steward': 'Стюард відновлення',
  'Diagnoses and recovers tasks left in broken state by workers.': 'Діагностує та відновлює завдання, залишені виконавцями у несправному стані.',
  'Custom Steward': 'Власний стюард',
  'User-defined steward with a workflow template executed when triggers fire.': 'Стюард, визначений користувачем, із шаблоном робочого процесу, що виконується після спрацювання тригерів.',
  'Short-lived worker spawned per task, reports to Director.': 'Короткоживучий виконавець, створений для завдання, звітує директору.',
  'Long-lived worker that handles multiple tasks, human-supervised.': 'Довгоживучий виконавець, який обробляє кілька завдань під наглядом людини.',
  Sunday: 'Неділя',
  Monday: 'Понеділок',
  Tuesday: 'Вівторок',
  Wednesday: 'Середа',
  Thursday: 'Четвер',
  Friday: 'П’ятниця',
  Saturday: 'Субота',
  Minutes: 'Хвилини',
  'Runs every N minutes': 'Запускається кожні N хвилин',
  Hourly: 'Щогодини',
  'Runs every N hours': 'Запускається кожні N годин',
  Daily: 'Щодня',
  'Runs every N days': 'Запускається кожні N днів',
  Weekly: 'Щотижня',
  'Runs once every week': 'Запускається раз на тиждень',
  Monthly: 'Щомісяця',
  'Runs once every month': 'Запускається раз на місяць',
  'Write a cron expression directly': 'Введіть вираз cron безпосередньо',
  'Failed to rename agent': 'Не вдалося перейменувати агента',
  'Failed to create task': 'Не вдалося створити завдання',
  'Failed to start agent': 'Не вдалося запустити агента',
  'Quick Actions': 'Швидкі дії',
  'View real-time activity feed': 'Переглянути стрічку активності в реальному часі',
  'View and manage tasks': 'Переглядати та керувати завданнями',
  'View and manage agents': 'Переглядати та керувати агентами',
  'Go to Stewards': 'Перейти до стюардів',
  'View steward agents': 'Переглянути агентів-стюардів',
  'Terminal multiplexer view': 'Подання мультиплексора термінала',
  'View workflow templates': 'Переглянути шаблони робочих процесів',
  'View performance metrics': 'Переглянути показники продуктивності',
  'App preferences and configuration': 'Параметри та конфігурація застосунку',
  'View and manage plans': 'Переглядати та керувати планами',
  'Review and merge agent work': 'Перевіряти та зливати роботу агентів',
  'Create a new task': 'Створити нове завдання',
  'View Unassigned Tasks': 'Переглянути непризначені завдання',
  'Tasks waiting for assignment': 'Завдання, що очікують призначення',
  'View In Progress Tasks': 'Переглянути завдання в роботі',
  'View Awaiting Merge': 'Переглянути завдання, що очікують злиття',
  'Tasks ready for merge review': 'Завдання, готові до перевірки злиття',
  'Register a new agent': 'Зареєструвати нового агента',
  'Create a new steward agent': 'Створити нового агента-стюарда',
  'Start All Agents': 'Запустити всіх агентів',
  'Start all registered agents': 'Запустити всіх зареєстрованих агентів',
  'Stop All Agents': 'Зупинити всіх агентів',
  'Stop all running agents': 'Зупинити всіх запущених агентів',
  'View Templates': 'Переглянути шаблони',
  'Browse workflow templates': 'Переглянути шаблони робочих процесів',
  'View Active Workflows': 'Переглянути активні робочі процеси',
  'Running workflow instances': 'Запущені екземпляри робочих процесів',
  'Refresh Data': 'Оновити дані',
  'Refresh all data from server': 'Оновити всі дані із сервера',
  'Open Director Terminal': 'Відкрити термінал директора',
  'Open the Director terminal panel': 'Відкрити панель термінала директора',
  'Maximize Director Panel': 'Розгорнути панель директора',
  'Toggle maximize/restore the Director panel': 'Розгорнути або відновити панель директора',
  Preferences: 'Параметри',
  'User preferences': 'Параметри користувача',
  'Workspace Settings': 'Налаштування робочого простору',
  'Workspace configuration': 'Конфігурація робочого простору',
  'Switch to Light Theme': 'Перемкнутися на світлу тему',
  'Use light color theme': 'Використовувати світлу кольорову тему',
  'Switch to Dark Theme': 'Перемкнутися на темну тему',
  'Use dark color theme': 'Використовувати темну кольорову тему',
  'Use System Theme': 'Використовувати системну тему',
  'Follow system color preference': 'Використовувати системні налаштування кольорів',
  'Command Palette': 'Палітра команд',
  'Match Case': 'Враховувати регістр',
  'Whole Word': 'Ціле слово',
  'Use Regular Expression': 'Використовувати регулярний вираз',
  'Quick File Open': 'Швидке відкриття файла',
  Markdown: 'Markdown',
  JSON: 'JSON',
  'Search failed': 'Помилка пошуку',
  'Failed to move file': 'Не вдалося перемістити файл',
  'Use Regex': 'Використовувати Regex',
  'Built-in': 'Вбудовані',
  Installed: 'Встановлені',
  'Could not load extension details.': 'Не вдалося завантажити відомості про розширення.',
  'Collapse sidebar': 'Згорнути бічну панель',
  'Expand sidebar': 'Розгорнути бічну панель',
  'Dismiss notification': 'Закрити сповіщення',
  'Navigating…': 'Перехід…',
  'Enter task title...': 'Введіть назву завдання…',
  'Describe the task in detail... (supports Markdown)': 'Опишіть завдання докладно… (підтримується Markdown)',
  'Remove assignee filter': 'Видалити фільтр виконавця',
  'Reset task': 'Скинути завдання',
  'Save (Cmd+S)': 'Зберегти (Cmd+S)',
  'Navigation menu': 'Меню навігації',
  'Failed to create agent': 'Не вдалося створити агента',
  'Failed to create pool': 'Не вдалося створити пул',
  'Failed to update pool': 'Не вдалося оновити пул',
  'Failed to fetch workspace tree': 'Не вдалося отримати дерево робочого простору',
  'Failed to load workspace': 'Не вдалося завантажити робочий простір',
  'Failed to open workspace': 'Не вдалося відкрити робочий простір',
  'Failed to refresh workspace': 'Не вдалося оновити робочий простір',
  'Failed to read file': 'Не вдалося прочитати файл',
  'Failed to write file': 'Не вдалося записати файл',
  'Failed to delete file': 'Не вдалося видалити файл',
  'Failed to rename file': 'Не вдалося перейменувати файл',
  'Failed to create folder': 'Не вдалося створити папку',
  'Refresh Activity': 'Оновити активність',
  'Connection failed': 'Підключення не вдалося',
  'Failed to connect': 'Не вдалося підключитися',
  Branch: 'Гілка',
  'All Tasks': 'Усі завдання',
  'Strategic agents that create and assign tasks': 'Стратегічні агенти, які створюють і призначають завдання',
  'Long-lived workers that handle multiple tasks': 'Довгоживучі виконавці, які обробляють кілька завдань',
  'Short-lived workers spawned per task': 'Короткоживучі виконавці, створені для окремих завдань',
  'Pools control how many agents can run concurrently': 'Пули визначають, скільки агентів можуть працювати одночасно',
  Extensions: 'Розширення',
  'Failed to initialize editor': 'Не вдалося ініціалізувати редактор',
  'Failed to save file': 'Не вдалося зберегти файл',
  'Failed to create': 'Не вдалося створити',
  'Click to view in inbox': 'Натисніть, щоб переглянути у вхідних',
  'Failed to send reply. Please try again.': 'Не вдалося надіслати відповідь. Спробуйте ще раз.',
  'No merge requests': 'Запитів на злиття немає',
  'When agents complete tasks, their work will appear here for review and merging.': 'Коли агенти завершать завдання, їхня робота з’явиться тут для перевірки та злиття.',
  'No requests need review': 'Немає запитів, що потребують перевірки',
  'All merge requests have been reviewed. Nice work!': 'Усі запити на злиття перевірено. Чудова робота!',
  'No tests running': 'Тести не виконуються',
  'No merge requests are currently running tests.': 'Наразі жоден запит на злиття не виконує тести.',
  'No conflicts': 'Конфліктів немає',
  'No merge requests have conflicts. All clear!': 'У запитах на злиття немає конфліктів. Усе гаразд!',
  'No merged requests': 'Злитих запитів немає',
  'No merge requests have been merged yet.': 'Запити на злиття ще не об’єднувалися.',
  'The conversation has been updated': 'Розмову оновлено',
  'The channel has been permanently deleted': 'Канал видалено назавжди',
  'Last 7 days': 'Останні 7 днів',
  'Last 14 days': 'Останні 14 днів',
  'Last 30 days': 'Останні 30 днів',
  'vs prev': 'порівняно з попереднім періодом',
  'Avg Completion': 'Середнє завершення',
  'Merge Queue': 'Черга злиття',
  'Total Tokens': 'Усього токенів',
  'Cache Hit Rate': 'Частота попадань у кеш',
  'Total Sessions': 'Усього сесій',
  'Estimated Cost': 'Орієнтовна вартість',
  'Choose how the interface looks': 'Виберіть вигляд інтерфейсу',
  Light: 'Світла',
  Dark: 'Темна',
  'Configure how you receive alerts': 'Налаштуйте отримання сповіщень',
  'Task completion alerts': 'Сповіщення про завершення завдань',
  'Notify when tasks are completed': 'Повідомляти після завершення завдань',
  'Agent health warnings': 'Попередження про стан агентів',
  'Notify when agents encounter issues': 'Повідомляти, коли агенти стикаються з проблемами',
  'Merge notifications': 'Сповіщення про злиття',
  'Notify when branches are merged': 'Повідомляти після злиття гілок',
  Sound: 'Звук',
  'Play a sound when notifications arrive': 'Відтворювати звук під час надходження сповіщень',
  'Quick access to common actions': 'Швидкий доступ до поширених дій',
  'Default provider and model for new agents': 'Типовий провайдер і модель для нових агентів',
  'Guided walkthrough of the dashboard': 'Покроковий огляд панелі керування',
  'Configure how agent worktrees are managed': 'Налаштуйте керування робочими деревами агентів',
  'Auto-merge passing branches': 'Автоматично зливати гілки з успішними тестами',
  'Automatically merge branches when tests pass': 'Автоматично зливати гілки після успішного проходження тестів',
  'Configure temporary task retention': 'Налаштувати зберігання тимчасових завдань',
  'Configure automated steward execution': 'Налаштувати автоматизоване виконання стюардів',
  'Automatically merges completed branches': 'Автоматично зливає завершені гілки',
  'Docs Steward': 'Стюард документації',
  'Maintains and updates documentation': 'Підтримує та оновлює документацію',
  'Reset all settings to their default values': 'Скинути всі налаштування до типових значень',
  'Configure director agent behavior': 'Налаштувати поведінку агента-директора',
  'Auto-forward inbox messages': 'Автоматично пересилати повідомлення з вхідних',
  'Forward new messages to the director': 'Пересилати нові повідомлення директору',
  'Controls how agents merge code and what permissions they have': 'Керує способом злиття коду агентами та їхніми дозволами',
  'Failed to switch project': 'Не вдалося перемкнути проєкт',
  'Failed to add project': 'Не вдалося додати проєкт',
  'Failed to remove project': 'Не вдалося видалити проєкт',
  'No tasks yet': 'Завдань ще немає',
  'Create your first task to get started. Tasks can be assigned to agents and tracked through completion.': 'Створіть перше завдання, щоб почати. Завдання можна призначати агентам і відстежувати до завершення.',
  'No backlog tasks': 'У беклозі немає завдань',
  'No tasks are currently in the backlog. Create a task with backlog status to see it here.': 'Наразі в беклозі немає завдань. Створіть завдання зі станом «беклог», щоб побачити його тут.',
  'No unassigned tasks': 'Непризначених завдань немає',
  'All tasks have been assigned to agents. Create a new task or unassign an existing one.': 'Усі завдання призначено агентам. Створіть нове завдання або скасуйте призначення наявного.',
  'No tasks are currently assigned and waiting to start. Assign a task to an agent to see it here.': 'Наразі немає призначених завдань, що очікують запуску. Призначте завдання агенту, щоб побачити його тут.',
  'No tasks in progress': 'Немає завдань у роботі',
  'No agents are currently working on tasks. Start a task to see it here.': 'Наразі жоден агент не працює над завданнями. Запустіть завдання, щоб побачити його тут.',
  'No completed tasks': 'Завершених завдань немає',
  'No tasks have been completed yet. Keep working on those tasks!': 'Завдання ще не завершено. Продовжуйте роботу!',
  'No tasks awaiting merge': 'Немає завдань, що очікують злиття',
  'No completed tasks are waiting to be merged. Completed task branches will appear here.': 'Немає завершених завдань, що очікують злиття. Гілки завершених завдань з’являться тут.',
  'Item not found': 'Елемент не знайдено',
  'Failed to refresh projects': 'Не вдалося оновити проєкти',
  'Failed to fetch projects': 'Не вдалося отримати проєкти',
  'Failed to register project': 'Не вдалося зареєструвати проєкт',
  Text: 'Текст',
  Active: 'Активний',
  Test: 'Тест',
  'Block Quote': 'Цитата з блоком',
  'Make text bold': 'Зробити текст напівжирним',
  'Make text italic': 'Зробити текст курсивом',
  'Format as inline code': 'Форматувати як вбудований код',
  'Insert a code block': 'Вставити блок коду',
  'Insert a block quote': 'Вставити цитату з блоком',
  'Create a simple bullet list': 'Створити простий маркований список',
  'Create a numbered list': 'Створити нумерований список',
  Emoji: 'Емодзі',
  'Insert an emoji': 'Вставити емодзі',
  'Reference a task': 'Додати посилання на завдання',
  'Reference a document': 'Додати посилання на документ',
  Activate: 'Активувати',
  Complete: 'Завершити',
  'Reopen as Draft': 'Повторно відкрити як чернетку',
  Remaining: 'Залишилося',
  'Custom error': 'Власна помилка',
  Mon: 'Пн',
  Tue: 'Вт',
  Wed: 'Ср',
  Thu: 'Чт',
  'Failed to load': 'Не вдалося завантажити',
  'Error loading': 'Помилка завантаження',
  'Mark Failed': 'Позначити як невдале',
  'Reset to Pending': 'Скинути до стану «очікує»',
  'Tasks currently being worked on': 'Завдання, над якими зараз працюють',
  'New terminal': 'Новий термінал',
  'Hide terminal': 'Приховати термінал',
  'Emergency Stop': 'Аварійна зупинка',
  'Task Board': 'Дошка завдань',
  'All work items live here. Switch between list and Kanban views, filter by status tabs, search, sort, and group tasks however you like.': 'Усі робочі елементи знаходяться тут. Перемикайтеся між списком і Канбаном, фільтруйте за вкладками станів, шукайте, сортуйте та групуйте завдання як завгодно.',
  'Create Tasks': 'Створення завдань',
  'Status Tabs': 'Вкладки станів',
  'Filter tasks by lifecycle stage.': 'Фільтруйте завдання за етапом життєвого циклу.',
  'Task Details': 'Деталі завдання',
  'Plans & Roadmap': 'Плани та дорожня карта',
  'Plan Details': 'Деталі плану',
  'When agents complete work, their branches appear here. Review diffs, approve, request changes, or merge directly.': 'Коли агенти завершують роботу, їхні гілки з’являються тут. Переглядайте diff, підтверджуйте, запитуйте зміни або зливайте безпосередньо.',
  'Agent Registry': 'Реєстр агентів',
  'Create Agents': 'Створення агентів',
  'Agent Provider & Model': 'Провайдер і модель агента',
  'Layout Presets': 'Набори макетів',
  'Choose single, columns, rows, or grid layouts. Add panes to monitor multiple agents side by side.': 'Виберіть одноколонковий, колоночний, рядковий або сітковий макет. Додавайте панелі, щоб стежити за кількома агентами поруч.',
  'Meet the Director': 'Знайомство з директором',
  'Director Tabs': 'Вкладки директора',
  'Each tab is a separate director session. Click (+) to create new directors, right-click a tab to delete one.': 'Кожна вкладка є окремою сесією директора. Натисніть (+), щоб створити нового директора, або клацніть вкладку правою кнопкою, щоб видалити його.',
  'The pickaxe icon triggers backlog sifting — the director reads your task backlog, prioritizes it, and creates plans for your agents.': 'Піктограма кирки запускає опрацювання беклогу — директор читає ваш беклог завдань, визначає пріоритети та створює плани для агентів.',
  'Start the Director': 'Запуск директора',
  'Team Messages': 'Повідомлення команди',
  'Slack-style channels for team communication. Create channels, send messages to agents, and keep conversations organized with threading.': 'Канали для командного спілкування у стилі Slack. Створюйте канали, надсилайте повідомлення агентам і впорядковуйте розмови за допомогою гілок.',
  'Send Messages': 'Надсилання повідомлень',
  'Select a channel and type a message in the composer. Attach documents, embed tasks, and use threads to keep conversations organized.': 'Виберіть канал і введіть повідомлення у редакторі. Прикріплюйте документи, вбудовуйте завдання та використовуйте гілки для впорядкування розмов.',
  'Document Library': 'Бібліотека документів',
  'Edit Documents': 'Редагування документів',
  'Your personal feed of @mentions, direct messages, and agent notifications. Filter, archive, and reply from one place.': 'Ваша стрічка згадок через @, прямих повідомлень і сповіщень агентів. Фільтруйте, архівуйте та відповідайте в одному місці.',
  'The bell icon shows real-time alerts: approval requests, agent errors, and important events.': 'Піктограма дзвіночка показує сповіщення в реальному часі: запити на підтвердження, помилки агентів і важливі події.',
  'Code Editor': 'Редактор коду',
  'A full Monaco editor with LSP support. Browse files, edit code with syntax highlighting and completions, and install extensions.': 'Повноцінний редактор Monaco з підтримкою LSP. Переглядайте файли, редагуйте код із підсвічуванням синтаксису та автодоповненням, встановлюйте розширення.',
  'Create reusable workflow templates (playbooks) and monitor active workflow execution with dependency tracking and progress visualization.': 'Створюйте багаторазові шаблони робочих процесів (плейбуки) та стежте за їхнім виконанням із відстеженням залежностей і візуалізацією прогресу.',
  'Create Workflow Templates': 'Створення шаблонів робочих процесів',
  'Metrics Dashboard': 'Панель метрик',
  'Track task throughput, agent performance, and provider usage over time. Use the time range selector to zoom into trends.': 'Відстежуйте пропускну здатність завдань, продуктивність агентів і використання провайдерів у часі. Використовуйте вибір діапазону часу для масштабування тенденцій.',
  'Press Cmd+K from anywhere to navigate pages, create tasks, toggle panels, and access every action without touching the mouse.': 'Натискайте Cmd+K будь-де, щоб переходити між сторінками, створювати завдання, перемикати панелі та отримувати доступ до всіх дій без миші.',
  'Workflow Presets': 'Набори робочих процесів',
  'You have seen the full power of Stoneforge. Start by opening the Director panel and starting a session -- it will read your backlog and begin orchestrating work. Press Cmd+K anytime to find any feature.': 'Ви побачили всі можливості Stoneforge. Почніть із відкриття панелі директора та запуску сесії — він прочитає ваш беклог і почне оркеструвати роботу. Натискайте Cmd+K у будь-який момент, щоб знайти потрібну функцію.',
  'Resume failed': 'Не вдалося відновити',
  'Task completed': 'Завдання завершено',
  'Merged to main': 'Злито в main',
  'Needs Review': 'Потребує перевірки',
  Conflicts: 'Конфлікти',
  Approvals: 'Підтвердження',
  Operators: 'Оператори',
  'Worker Agents': 'Агенти-виконавці',
  'Assigned To': 'Призначено',
  'auto-detect': 'автовизначення',
  'Welcome to Stoneforge': 'Ласкаво просимо до Stoneforge',
  'Your command center -- see all active agents, tasks, and system health at a glance.': 'Ваш командний центр — переглядайте всіх активних агентів, завдання та стан системи одним поглядом.',
  'These indicators show active agents, in-progress tasks, and merge request pipeline health. A quick pulse check.': 'Ці індикатори показують активних агентів, завдання в роботі та стан конвеєра запитів на злиття. Швидка оцінка стану.',
  'Each card is a running agent showing its status, current task, and live output. Click one to open its terminal.': 'Кожна картка — це запущений агент із його станом, поточним завданням і поточним виводом. Натисніть картку, щоб відкрити термінал.',
  'Global Controls': 'Глобальні керування',
  'The pickaxe icon triggers backlog sifting — the director reads your task backlog, prioritizes work, and creates plans for your agents.': 'Піктограма кирки запускає опрацювання беклогу — директор читає ваш беклог завдань, визначає пріоритети роботи та створює плани для агентів.',
  'An error occurred while loading the application data.': 'Під час завантаження даних застосунку сталася помилка.',
  'Failed to load models. Try again later.': 'Не вдалося завантажити моделі. Спробуйте пізніше.',
  'There was an error loading your messages': 'Під час завантаження ваших повідомлень сталася помилка',
  'The header gives you the command palette (Cmd+K), daemon toggle, emergency stop, notifications, and theme switch -- available on every page.': 'У заголовку доступні палітра команд (Cmd+K), перемикач демона, аварійна зупинка, сповіщення та перемикач теми — на кожній сторінці.',
  "You can manually create tasks here, but you usually won't need to. Just give work to the Director and it will plan and create tasks for you automatically.": 'Ви можете створювати завдання вручну, але зазвичай це не потрібно. Передайте роботу директору — він автоматично спланує її та створить завдання.',
  'Plans group related tasks into a coordinated effort. Switch to Roadmap view for a timeline visualization.': 'Плани об’єднують пов’язані завдання в узгоджену роботу. Перемкніться на подання дорожньої карти, щоб переглянути часову шкалу.',
  'Meet your fleet: Directors orchestrate, Workers execute tasks, Stewards review code. Create, configure, and manage agents here.': 'Познайомтеся зі своїм флотом: директори оркеструють, виконавці виконують завдання, стюарди перевіряють код. Створюйте, налаштовуйте та керуйте агентами тут.',
  'A tmux-like multiplexer. Watch agents work in real time, interact with their terminals, or run commands yourself.': 'Мультиплексор у стилі tmux. Спостерігайте за роботою агентів у реальному часі, взаємодійте з їхніми терміналами або виконуйте команди самостійно.',
  'Process Messages': 'Опрацювати повідомлення',
  You: 'Ви',
  Orchestration: 'Оркестрація',
  'Failed to save playbook': 'Не вдалося зберегти плейбук',
  'Message...': 'Повідомлення…',
  'This action cannot be undone': 'Цю дію не можна скасувати',
  'You are about to delete the library "': 'Ви збираєтеся видалити бібліотеку «',
  'This library contains': 'Ця бібліотека містить',
  'Drop files to upload': 'Перетягніть файли для завантаження',
  'File paths will be inserted at cursor': 'Шляхи до файлів буде вставлено в позицію курсора',
  'Read Only': 'Лише читання',
};

const PATTERN_TRANSLATIONS: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
  [/^Remove tag\s+(.+)$/i, match => `Видалити тег ${match[1]}`],
  [/^Assigned:\s*(.+)$/i, match => `Призначено: ${match[1]}`],
  [/^Created\s+(.+)$/i, match => `Створено ${match[1]}`],
  [/^Start:\s*(.+)$/i, match => `Початок: ${match[1]}`],
  [/^End:\s*(.+)$/i, match => `Кінець: ${match[1]}`],
  [/^Updated\s+(.+)$/i, match => `Оновлено ${match[1]}`],
  [/^Started\s+(.+)$/i, match => `Запущено ${match[1]}`],
  [/^Loaded\s+(.+)\s+elements$/i, match => `Завантажено ${match[1]} елементів`],
  [/^Loading\s+(\d+)\s+events\.\.\.$/i, match => `Завантаження ${match[1]} подій…`],
  [/^(\d+)\s+of\s+(\d+)\s+events$/i, match => `${match[1]} з ${match[2]} подій`],
  [/^(\d+)\s+total\s+events$/i, match => `Усього подій: ${match[1]}`],
  [/^Created:\s*(.+)$/i, match => `Створено: ${match[1]}`],
  [/^Updated:\s*(.+)$/i, match => `Оновлено: ${match[1]}`],
  [/^Sort:\s*(.+)$/i, match => `Сортування: ${match[1]}`],
  [/^Show\s+(\d+)\s+per page$/i, match => `Показати ${match[1]} на сторінку`],
  [/^Showing\s+(\d+)\s+items?$/i, match => `Показано елементів: ${match[1]}`],
  [/^Showing\s+(\d+)-(\d+)\s+of\s+(\d+)$/i, match => `Показано ${match[1]}–${match[2]} з ${match[3]}`],
  [/^(\d+)\s+unread messages$/i, match => `Непрочитаних повідомлень: ${match[1]}`],
  [/^Workspace:\s*(.+)$/i, match => `Робочий простір: ${match[1]}`],
  [/^No files contain "(.+)"$/i, match => `Файлів, що містять «${match[1]}», не знайдено`],
  [/^No results for "(.+)"$/i, match => `Немає результатів для «${match[1]}»`],
  [/^No other steps available$/i, () => 'Немає інших доступних кроків'],
  [/^No enum values\. Variable accepts any value of its type\.$/i, () => 'Немає значень enum. Змінна приймає будь-яке значення свого типу.'],
  [/^Only one task remaining$/i, () => 'Залишилося лише одне завдання'],
  [/^Open \((\d+)\)$/i, match => `Відкриті (${match[1]})`],
  [/^In Progress \((\d+)\)$/i, match => `У процесі (${match[1]})`],
  [/^Blocked \((\d+)\)$/i, match => `Заблоковані (${match[1]})`],
  [/^Total events$/i, () => 'Усього подій'],
  [/^Failed to load\s+([^:]+):\s*(.*)$/i, match => {
    const fragment = match[1].trim().toLowerCase() === 'inbox'
      ? 'вхідні'
      : translateKnownFragment(match[1]) ?? match[1];
    return 'Не вдалося завантажити ' + fragment + ': ' + match[2].replace(/^Error:\s*/i, '');
  }],
  [/^Provider default\s+\((.+)\)$/i, match => `Типово для провайдера (${match[1]})`],
  [/^Loading\s+(.+)$/i, match => {
    const fragment = translateKnownFragment(match[1]);
    return fragment ? `Завантаження ${fragment}` : match[0];
  }],
  [/^Failed to load\s+(.+)$/i, match => {
    const fragment = translateKnownFragment(match[1]);
    return fragment ? `Не вдалося завантажити ${fragment}` : match[0];
  }],
  [/^Search\s+(.+)$/i, match => {
    const fragment = translateKnownFragment(match[1]);
    return fragment ? `Пошук ${fragment}` : match[0];
  }],
  [/^Go to\s+(.+)$/i, match => {
    const fragment = translateKnownFragment(match[1]);
    return fragment ? `Перейти: ${fragment}` : match[0];
  }],
  [/^View\s+(.+)$/i, match => {
    const fragment = translateKnownFragment(match[1]);
    return fragment ? `Переглянути ${fragment}` : match[0];
  }],
];

const FRAGMENT_TRANSLATIONS: Record<string, string> = {
  activity: 'активність',
  agents: 'агенти',
  channels: 'каналів',
  'chart data': 'дані графіка',
  charts: 'графіків',
  data: 'даних',
  documents: 'документів',
  dashboard: 'панель керування',
  dependencies: 'залежності',
  entities: 'сутностей',
  events: 'подій',
  files: 'файлів',
  inbox: 'вхідних',
  libraries: 'бібліотек',
  members: 'учасників',
  messages: 'повідомлень',
  metrics: 'метрики',
  'merge requests': 'запити на злиття',
  plan: 'план',
  plans: 'планів',
  projects: 'проєктів',
  provider: 'провайдера',
  'ready tasks': 'готові завдання',
  ready: 'готові',
  results: 'результатів',
  sessions: 'сесій',
  settings: 'налаштування',
  stats: 'статистики',
  tasks: 'завдань',
  teams: 'команди',
  timeline: 'часова шкала',
  users: 'користувачів',
  workflow: 'робочий процес',
  'workflow preset': 'набір робочого процесу',
  workflows: 'робочих процесів',
  workspaces: 'робочі простори',
  'executable paths': 'шляхи до виконуваних файлів',
};

function translateKnownFragment(fragment: string): string | undefined {
  const match = fragment.match(/^(.*?)(\.\.\.|\.)?$/);
  if (!match) return undefined;
  const translated = FRAGMENT_TRANSLATIONS[match[1].trim().toLowerCase()];
  const suffix = match[2] === '...' ? '…' : match[2] ?? '';
  return translated ? `${translated}${suffix}` : undefined;
}

function preserveWhitespace(original: string, translated: string): string {
  const leading = original.match(/^\s*/)?.[0] ?? '';
  const trailing = original.match(/\s*$/)?.[0] ?? '';
  return `${leading}${translated}${trailing}`;
}

export function translateUserText(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return value;

  const exact = EXACT_TRANSLATIONS[trimmed] ?? ADDITIONAL_TRANSLATIONS[trimmed];
  if (exact) return preserveWhitespace(value, exact);

  for (const [pattern, translate] of PATTERN_TRANSLATIONS) {
    const match = trimmed.match(pattern);
    if (match) return preserveWhitespace(value, translate(match));
  }

  return value;
}

const TRANSLATABLE_ATTRIBUTES = ['aria-label', 'placeholder', 'title', 'alt'];
const PROTECTED_UI_SELECTORS = [
  'code',
  'pre',
  'script',
  'style',
  '[contenteditable="true"]',
  '[data-user-content]',
  '[data-technical-content]',
  '[data-code-content]',
  '[data-file-path]',
  '.monaco-editor',
  '.ProseMirror',
].join(', ');
const lastTranslatedText = new WeakMap<Text, string>();

function translateNode(node: Node): void {
  if (node.nodeType === Node.TEXT_NODE) {
    const textNode = node as Text;
    const parent = textNode.parentElement;
    if (!parent || parent.closest(PROTECTED_UI_SELECTORS)) return;

    const current = textNode.nodeValue ?? '';
    if (current === lastTranslatedText.get(textNode)) return;

    const translated = translateUserText(current);
    if (translated !== current) {
      lastTranslatedText.set(textNode, translated);
      textNode.nodeValue = translated;
    }
    return;
  }

  if (node.nodeType !== Node.ELEMENT_NODE) return;
  const element = node as Element;
  if (element.matches(PROTECTED_UI_SELECTORS) || element.closest(PROTECTED_UI_SELECTORS)) return;
  for (const attribute of TRANSLATABLE_ATTRIBUTES) {
    const value = element.getAttribute(attribute);
    if (!value) continue;
    const translated = translateUserText(value);
    if (translated !== value) element.setAttribute(attribute, translated);
  }
  for (const child of Array.from(element.childNodes)) translateNode(child);
}

export function installUkrainianInterface(root?: HTMLElement | null): () => void {
  if (typeof document === 'undefined') return () => undefined;
  const container = root ?? document.body;
  if (!container) return () => undefined;
  if (document.documentElement.dataset.localeInstalled === 'uk') return () => undefined;

  document.documentElement.lang = 'uk';
  document.documentElement.dataset.localeInstalled = 'uk';
  translateNode(container);

  const observer = new MutationObserver(mutations => {
    for (const mutation of mutations) {
      if (mutation.type === 'attributes') translateNode(mutation.target);
      for (const node of Array.from(mutation.addedNodes)) translateNode(node);
      if (mutation.type === 'characterData') translateNode(mutation.target);
    }
  });

  observer.observe(container, {
    subtree: true,
    childList: true,
    characterData: true,
    attributes: true,
    attributeFilter: TRANSLATABLE_ATTRIBUTES,
  });

  return () => observer.disconnect();
}
